stages:
  - build

variables:
  REGISTRY: registry.gitlab.com
  IMAGE: ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  CHECK_GIT: git diff origin/master --name-only

before_script:
  # Enable GitLab registry
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${REGISTRY}

.build_template: &build_definition
  stage: build
  script:
    - >
      if  ${CHECK_GIT} | grep "^versions/${OS}_${VER}$" || \
          ${CHECK_GIT} | grep "^dockerfiles/${OS}_${DVER}$" || \
          ${CHECK_GIT} | grep "^files/"
      then
        make -f .gitlab.mk build
      fi;

'alpine 3.5 1.x':
  <<: *build_definition
  variables:
    OS: 'alpine_3.5'
    TAG: '1'
    VER: '1.x'
    DVER: '1.x'
    PORT: 3110

'alpine 3.5 2.x':
  <<: *build_definition
  variables:
    OS: 'alpine_3.5'
    TAG: '2'
    VER: '2.x'
    DVER: '2.x'
    PORT: 3120

'alpine 3.5 2.1':
  <<: *build_definition
  variables:
    OS: 'alpine_3.5'
    TAG: '2.1'
    VER: '2.1'
    DVER: '2.2'
    PORT: 3121

'alpine 3.5 2.2':
  <<: *build_definition
  variables:
    OS: 'alpine_3.5'
    TAG: '2.2'
    VER: '2.2'
    DVER: '2.2'
    PORT: 3122

'centos 7 1.x':
  <<: *build_definition
  variables:
    OS: 'centos_7'
    TAG: '1.x-centos7'
    VER: '1.x'
    DVER: '1.x'
    PORT: 3210

'centos 7 2.x':
  <<: *build_definition
  variables:
    OS: 'centos_7'
    TAG: '2.x-centos7'
    VER: '2.x'
    DVER: '2.x'
    PORT: 3220

