stages:
  - build

variables:
  REGISTRY: registry.gitlab.com
  IMAGE: ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

before_script:
  # Enable GitLab registry
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${REGISTRY}

.build_template: &build_definition
  stage: build
  script:
    - >
      if git diff origin/master --name-only | grep "^${DIR}/" ; then
        make -f .gitlab.mk build
      fi;

'1.x':
  <<: *build_definition
  variables:
    TAG: '1'
    DIR: '1.x'
    PORT: 3301

'2.x':
  <<: *build_definition
  variables:
    TAG: '2'
    DIR: '2.x'
    PORT: 3302

'2.1':
  <<: *build_definition
  variables:
    TAG: '2.1'
    DIR: '2.1'
    PORT: 3321

'2.2':
  <<: *build_definition
  variables:
    TAG: '2.2'
    DIR: '2.2'
    PORT: 3322

